import {
  AboutSection,
  Title,
  SvgIcon,
  ImgWrap,
  SubDescription,
  Banner,
  TextWrap,
} from './About.styled';

import { Description } from './Description/Description';

import icon from '../../assets/icons/svg-sprite.svg';

import imageMobile1x from '../../assets/images/about/about-mobile@1x.png';
import imageMobile2x from '../../assets/images/about/about-mobile@2x.png';
import imageTablet1x from '../../assets/images/about/about-tablet@1x.png';
import imageTablet2x from '../../assets/images/about/about-tablet@2x.png';
import imageDesktop1x from '../../assets/images/about/about-desktop@1x.png';
import imageDesktop2x from '../../assets/images/about/about-desktop@2x.png';

export const About = () => {
  return (
    <AboutSection>
      <TextWrap>
        <Title>
          a Story that started <br />
          with&nbsp;
          <span>
            one <br /> simple <span>ape</span>
          </span>
        </Title>
        <Description />
      </TextWrap>

      <SubDescription>
        <SvgIcon>
          <use href={icon + `#icon-cross`}></use>
        </SvgIcon>
        EACH ARTWORK IN THE <br />
        COLLECTION TELLS A STORY OF <br /> ONE JOURNEY. ARTS ARE <br />
        RANDOMLY GENERATED BY <span>USERS</span>
      </SubDescription>
      <ImgWrap>
        <picture>
          <source
            srcSet={`${imageDesktop1x} 1x,  ${imageDesktop2x} 2x`}
            media="(min-width: 1280px)"
          />
          <source
            srcSet={`${imageTablet1x} 1x,  ${imageTablet2x} 2x`}
            media="(min-width: 768px)"
          />
          <source srcSet={`${imageMobile1x} 1x,  ${imageMobile2x} 2x`} />

          <img src={imageDesktop1x} alt="Monkey" />
        </picture>
      </ImgWrap>
      <Banner>
        <p>
          HAVE NO LIMITS{' '}
          <SvgIcon>
            <use href={icon + `#icon-cross`}></use>
          </SvgIcon>
        </p>

        <p>
          Break rules{' '}
          <SvgIcon>
            <use href={icon + `#icon-cross`}></use>
          </SvgIcon>
        </p>
        <p>
          Destroy stereotypes{' '}
          <SvgIcon>
            <use href={icon + `#icon-cross`}></use>
          </SvgIcon>
        </p>

        <p>
          HAVE NO LIMITS{' '}
          <SvgIcon>
            <use href={icon + `#icon-cross`}></use>
          </SvgIcon>
        </p>

        <p>
          Break rules{' '}
          <SvgIcon>
            <use href={icon + `#icon-cross`}></use>
          </SvgIcon>
        </p>
        <p>
          Destroy stereotypes{' '}
          <SvgIcon>
            <use href={icon + `#icon-cross`}></use>
          </SvgIcon>
        </p>
      </Banner>
    </AboutSection>
  );
};
