export * from './Container/Container';
export * from './Header/Header';
export * from './Hero/Hero';
export * from './About/About';
export * from './MindMap/MindMap';
export * from './Faq/Faq';
export * from './Arts/Arts';
export * from './Contact/Contact.jsx';
export * from './Footer/Footer';
